$(function(){
    $("button").on({
        mouseover:function(){
            $(this).css({
                left:(Math.random()*500)+"px",
                top:(Math.random()*550)+"px",
            });
        }
    });
});